# Generated by Django 5.2.7 on 2025-11-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.post'),
            preserve_default=False,
        ),
    ]
